### PR TITLE
#166187870 user can search and filter an article

### PR DESCRIPTION
**Pull request by jennizalwango**
#### What does this PR do?
- user can search an article by title, author, and tag
- user can filter an article by title, author, and tag
#### Description of the task?
- user can search for an article for by title
- user can  be able to filter an article by either title, author and  by filters
#### How can this be manually tested?
- Provide either a title, author or a search for example
Screenshot 2019-06-20 at 10 23 23 PM

#### what are the relevant pivotal tracker stories
[#166187870]

### CODE REVIEW

**Review by alexxsanya — COMMENTED** [review]
@jennizalwango well done with current work. tested and it is working as expected.

**Review by neelxie — APPROVED** [review]
@jennizalwango I have tried it out and it seems to work perfect on my end. Good stuff.

**Review by HabibSentongo — APPROVED** [review]
Everything works perfectly, good work @jennizalwango

**Review by alexxsanya — APPROVED** [review]
@jennizalwango this is working as expected. well done

**Review by Emmanuelaaron — APPROVED** [review]
It works well on my end.
we are good to go

**Pull request merged**
