### PR TITLE
#166187869 :Pagination support for articles

### PR DESCRIPTION
**Pull request by jennizalwango**
#### What this PR does?
- Support Pagination for articles
### Description of the task?
- user should be able to get articles on different pages
#### How can this manually be tested?
- Run `git fetch origin ft-Pagination-166187869`
- Run `python manage.py runserver`
- Now test out the following
- when there are already created articles
- Run `http://127.0.0.1:8000/api/articles/` and you will click on the link that has a ''next'' and "previous" to get the articles
Screenshot 2019-06-19 at 2 38 08 PM

- Then you will send it again, there you will be able to get the articles and each page contains 10 article.

#### What are the relevant pivotal tracker stories
 [Finishes #166187869]

### CODE REVIEW

**Review by HabibSentongo — APPROVED** [review]
Wow, this is good work @jennizalwango, I have tested and the pagination functions perfectly well.

**Review by Emmanuelaaron — APPROVED** [review]
Great work @jennizalwango

**Review by neelxie — APPROVED** [review]
Good work @jennizalwango I commend you for the work done.

**Review by alexxsanya — APPROVED** [review]
@jennizalwango  great work on this.

**Pull request merged**
