### PR TITLE
#166187851 Document API with Swagger

### PR DESCRIPTION
**Pull request by HabibSentongo**
**What does this PR do?**
Document API endpoints.

**Description of Task to be completed?**
- install drf-yasg and drf-yasg[validation] packages
- add documentation endpoints to urls.py file
- add drf-yasg to installed apps in settings.py
- add documentation schema to the views functions
- update the requirements.txt document to include the new packages

**How should this be manually tested?**
- Fetch this branch using `git fetch origin ft-swagger-documentation-166187851`
- Checkout to this branch using `ft-swagger-documentation-166187851`
- Install all the app requirements using `pip install -r requirements.txt`
- Run the project using `python3 manage.py runserver`
- View the documentation in your internet browser by visiting `http://127.0.0.1:8000/swagger/` or `http://127.0.0.1:8000/docs/`

**Any background context you want to provide?**
I have added two swagger documentation formats for anyone to use what they prefer.

**What are the relevant pivotal tracker stories?**
Story ID - [166187851](https://www.pivotaltracker.com/n/projects/2350340/stories/166187851)

### CODE REVIEW

**Review by alexxsanya — COMMENTED** [review]
Hi @HabibSentongo, I can't happen to run this application following your procedures, seem like you added some packages which are failing the app from running. kindly check it out.

Screenshot 2019-06-01 at 12 30 55

**Comment by HabibSentongo** [comment]
Thank you @alexxsanya, I'm working on correcting the packages in the
requirements.txt file.

**Comment by alexxsanya** [comment]
> Thank you @alexxsanya, I'm working on correcting the packages in the requirements.txt file.

@HabibSentongo I happen to finally run your branch but I had to rectify some two issues.
1. No Module Named: 'psycopg2.extention'  
**** `you still have both the old psycopg2==2.7.7 and the new psycopg2-binary==2.8.2 as you can see in your requirements.txt on line 29 & 30 which are conflicting with each other. ` 

2. CORS_ORIGIN_WHITELIST is missing scheme or netloc
**** ` (corsheaders.E013) Origin '0.0.0.0:4000' in CORS_ORIGIN_WHITELIST is missing scheme or netloc.  HINT: Add a scheme (e.g. https://) or netloc (e.g. example.com).***`

Try running this:

- `$ pip3 uninstall psycopg2`
- `$ pip3 uninstall psycopg2-binary`
- `$ pip3 install psycopg2-binary`
- `$ pip freeze => requirements.txt `(_for the file to be updated with the changes_)
- Update the **authors/settings.py** lines 128 to 131 with the code below

```
CORS_ORIGIN_WHITELIST = (
    'http://0.0.0.0:4000',
    'http://localhost:4000',
)
```

I hope it fixes this issue completely and also.

**Comment by alexxsanya** [comment]
> > Thank you @alexxsanya, I'm working on correcting the packages in the requirements.txt file.

**Comment by alexxsanya** [comment]
> Thank you @alexxsanya, I'm working on correcting the packages in the requirements.txt file.

@HabibSentongo I happen to finally run your branch but I had to rectify some two issues.
1. No Module Named: 'psycopg2.extention'  
**** `you still have both the old psycopg2==2.7.7 and the new psycopg2-binary==2.8.2 as you can see in your requirements.txt on line 29 & 30 which are conflicting with each other. ` 

2. CORS_ORIGIN_WHITELIST is missing scheme or netloc
**** ` (corsheaders.E013) Origin '0.0.0.0:4000' in CORS_ORIGIN_WHITELIST is missing scheme or netloc.  HINT: Add a scheme (e.g. https://) or netloc (e.g. example.com).***`

Try running this:

- `$ pip3 uninstall psycopg2`
- `$ pip3 uninstall psycopg2-binary`
- `$ pip3 install psycopg2-binary`
- `$ pip freeze => requirements.txt `(_for the file to be updated with the changes_)
- Update the **authors/settings.py** lines 128 to 131 with the code below

```
CORS_ORIGIN_WHITELIST = (
    'http://0.0.0.0:4000',
    'http://localhost:4000',
)
```

I hope it fixes this issue completely and also.

**Comment by alexxsanya** [comment]
> **What does this PR do?**
> Document API endpoints.
> 
> **Description of Task to be completed?**
> 
> * install drf-yasg and drf-yasg[validation] packages
> * add documentation endpoints to urls.py file
> * add drf-yasg to installed apps in settings.py
> * add documentation schema to the views functions
> * update the requirements.txt document to include the new packages
> 
> **How should this be manually tested?**
> 
> * Fetch this branch using `git fetch origin ft-swagger-documentation-166187851`
> * Checkout to this branch using `ft-swagger-documentation-166187851`
> * Run the project using `python3 manage.py runserver`
> * View the documentation in your internet browser by visiting `http://127.0.0.1:8000/swagger/` or `http://127.0.0.1:8000/docs/`
> 
> **Any background context you want to provide?**
> I have added two swagger documentation formats for anyone to use what they prefer.
> 
> **What are the relevant pivotal tracker stories?**
> Story ID - [166187851](https://www.pivotaltracker.com/n/projects/2350340/stories/166187851)

kindly add another step to install the packages on which the changes you made are dependent on before `the run the project step` , so that issues of packages missing are proactively handled from occurring.

**Comment by HabibSentongo** [comment]
Great thanks, I'll check out those suggestions when I get to my computer

**Review by alexxsanya — APPROVED** [review]
After working on the earlier comments. I believe we are good to go.

**Review by neelxie — APPROVED** [review]
I have checked it out the documentation and hence do applaud you for taking the extra effort to provide two implementations. Excellent work.

**Review by Emmanuelaaron — CHANGES_REQUESTED** [review]
Unfortunately following the steps on your PR, It has failed to work.
Screenshot 2019-06-05 at 14 16 56

**Comment by HabibSentongo** [comment]
@Emmanuelaaron this is because you have not installed the packages using the requirements.txt file

**Comment by Emmanuelaaron** [comment]
> Unfortunately following the steps on your PR, It has failed to work.
> Screenshot 2019-06-05 at 14 16 56

@HabibSentongo, under `How should this be manually tested?` just immediately after the step that says `Checkout to this branch using ft-swagger-documentation-166187851`, please include `$ pip install -r requirements.txt`. I had not done that. That's why I was getting the error above.

Other than that, my approval awaits when you make that change. thanks

**Comment by HabibSentongo** [comment]
> > Unfortunately following the steps on your PR, It has failed to work.
> > Screenshot 2019-06-05 at 14 16 56
> 
> @HabibSentongo, under `How should this be manually tested?` just immediately after the step that says `Checkout to this branch using ft-swagger-documentation-166187851`, please include `$ pip install -r requirements.txt`. I had not done that. That's why I was getting the error above.
> 
> Other than that, my approval awaits when you make that change. thanks

Thank you @Emmanuelaaron I have added the step

**Review by Emmanuelaaron — APPROVED** [review]
Cool, we are now good to go. well done!!!

**Pull request merged**
