### PR TITLE
#166187847  Intergrate travis with the README badge

### PR DESCRIPTION
**Pull request by jennizalwango**
#### What does this PR do?
Integrate Travis

#### Description of Task to be completed?
Integrate Travis with the README badge.

#### How should this be manually tested?
 Go to `ch-intergrate_Travis-166187847` branch
Then click on the badge that is appearing on the ReadMe
Then it should take you to Travis to show that the build is passing 

#### Any background context you want to provide?
Initially, the app was not integrated to Travis but now l have integrated Travis With the README

#### What are the relevant pivotal tracker stories?
 # [166187847](https://www.pivotaltracker.com/story/show/166187847)

### CODE REVIEW

**Review by alexxsanya — CHANGES_REQUESTED** [review]
@jennizalwango I find most of the things to be as expected. kindly squash the commits into one and I believe we shall be good to go.

**Comment by HabibSentongo** [comment]
> @jennizalwango I find most of the things to be as expected. kindly squash the commits into one and I believe we shall be good to go.

I have checked the badge and also clicked on it to redirect me to TravisCI to ensure it's on the right branch and I've confirmed all this is fine. So kindly squash your five commits into one so we can approve this for merging.

**Review by neelxie — COMMENTED** [review]
I have checked out the badge and everything looks good, so I guess after you working on Alex's feedback, I will approve.

**Comment by Emmanuelaaron** [comment]
Great work @jennizalwango though I do not find it logical to run the entire project on my local machine to see whether the chore is done. Would you please consider editing the `How should this be manually tested?` section to clicking on the badge to redirect me straight to TravisCI.
Plus implementing @alexxsanya 's feedback, I will approve your PR. thanks

**Comment by jennizalwango** [comment]
> @jennizalwango I find most of the things to be as expected. kindly squash the commits into one and I believe we shall be good to go.

@HabibSentongo  and @alexxsanya  this has been resolved

**Comment by jennizalwango** [comment]
> Great work @jennizalwango though I do not find it logical to run the entire project on my local machine to see whether the chore is done. Would you please consider editing the `How should this be manually tested?` section to clicking on the badge to redirect me straight to TravisCI.
> Plus implementing @alexxsanya 's feedback, I will approve your PR. thanks

@Emmanuelaaron l have resolved this and also implemented the feedback asked

**Review by Emmanuelaaron — APPROVED** [review]
Thanks @jennizalwango. We are good to go

**Review by HabibSentongo — APPROVED** [review]
Following your steps now in 'How can this be manually tested?', I have checked out the badge and also clicked on it to redirect me to TravisCI to ensure it's on the right branch and I've confirmed everything is fine

**Review by alexxsanya — APPROVED** [review]
@jennizalwango after squashing and working on your PR notice everything. I believe we can go ahead to merge to develop.

**Review by neelxie — APPROVED** [review]

**Pull request merged**
